# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

let
  plymouth-minecraft-theme =
    inputs.plymouth-minecraft-theme.packages.${pkgs.system}.plymouth-minecraft-theme;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Bootloader.
  #boot.loader.systemd-boot = {
  #  enable = lib.mkForce false;
  #};
  #boot.loader.grub = {
  #  enable = true;
  #  device = "nodev";
  #  efiSupport = true;
  #  memtest86.enable = true;
  #  minegrub-theme = {
  #    enable = true;
  #    splash = "100% Flakes!";
  #    background = "background_options/1.8  - [Classic Minecraft].png";
  #    boot-options-count = 4;
  #  };
  #};
  robins-nixos.efiboot = {
    enable = true;
    systemd-boot.enable = true;
    grub.enable = false;
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Enable "Silent Boot"
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
    "quiet"
    "splash"
    "boot.shell_on_fail"
    "loglevel=3"
    "rd.systemd.show_status=false"
    "rd.udev.log_level=3"
    "udev.log_priority=3"
  ];
  # Hide the OS choice for bootloaders.
  # It's still possible to open the bootloader list by pressing any key
  # It will just not appear on screen unless a key is pressed
  #boot.loader.timeout = 0;

  boot.initrd.systemd.enable = true;
  boot.plymouth = {
    enable = true;
    #themePackages = [
    #  plymouth-minecraft-theme
    #];
    #theme = "mc";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2cc16de1-3ae8-4b1f-bf43-d37e36946565";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
    ];
  };

  boot.initrd.luks.devices."luks-1aeeccac-4866-4ba7-b9e2-6778350c64fb".device =
    "/dev/disk/by-uuid/1aeeccac-4866-4ba7-b9e2-6778350c64fb";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A4E5-A27B";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/95f2bbda-b610-41b7-b403-ec9fef5d6aac"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
