# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

let
  plymouth-minecraft-theme =
    inputs.plymouth-minecraft-theme.packages.${pkgs.system}.plymouth-minecraft-theme;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Bootloader.
  # boot.loader.systemd-boot = {
  #   enable = lib.mkForce false;
  # };
  # boot.loader.grub = {
  #   enable = true;
  #   device = "nodev";
  #   efiSupport = true;
  #   memtest86.enable = true;
  #   minegrub-theme = {
  #     enable = true;
  #     splash = "100% Flakes!";
  #     background = "background_options/1.8  - [Classic Minecraft].png";
  #     boot-options-count = 4;
  #   };
  # };
  robins-nixos.efiboot = {
    enable = true;
    systemd-boot.enable = true;
    grub.enable = false;
  };

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Enable "Silent Boot"
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
    "quiet"
    "splash"
    "boot.shell_on_fail"
    "loglevel=3"
    "rd.systemd.show_status=false"
    "rd.udev.log_level=3"
    "udev.log_priority=3"
  ];
  # Hide the OS choice for bootloaders.
  # It's still possible to open the bootloader list by pressing any key
  # It will just not appear on screen unless a key is pressed
  #boot.loader.timeout = 0;

  boot.initrd.systemd.enable = true;
  boot.plymouth = {
    enable = true;
    #themePackages = [
    #  plymouth-minecraft-theme
    #];
    #theme = "mc";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cf95cda5-b649-4bfb-a1a4-fb648a315e74";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ba6c7829-a02d-47f0-a82f-97929a925c2f".device =
    "/dev/disk/by-uuid/ba6c7829-a02d-47f0-a82f-97929a925c2f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/38B7-470D";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/46f2fe2a-0b02-470d-858f-24042bcbc656"; }
  ];

  fileSystems."/media/games" = {
    device = "/dev/disk/by-uuid/1c20576c-31b1-4adb-9df7-f0c2d9d9bc57";
    fsType = "ext4";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
